eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: authservice
jwt:
  secret: t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWm
server:
  port: 9990
